import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { getDefaultSiteSettings } from '../site-settings/defaults.js';
import { resolveThemeFile } from '../theme/resolver.js';
import { applyVariantDefaultsToSiteSettings } from '../theme/variant-defaults.js';
import { readThemeFamily } from '../theme/palette.js';
import { classicDeprecationMessage } from '../theme/copy.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const LIB_PKG = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, '../../package.json'), 'utf8')
);

// Theme of a new project without --theme: a Base v2 form (classic themes are deprecated, Task 167).
export const DEFAULT_THEME = 'theme-editorial';

// Built-in environments seeded into every project. Legacy projects that carried
// local_test/staging keep those (they are merged in from the legacy config below)
// but they are no longer seeded as defaults.
const DEFAULT_ENVS = {
  development: { outputName: 'development', env: {} },
  production:  { outputName: 'production',  env: {} }
};

export function reinitProject({ projectPath, force = false } = {}) {
  const absPath = path.resolve(projectPath);
  const configPath = path.join(absPath, 'marbas-project.json');
  const legacyPath = path.join(absPath, '.marbas-site-project.json');

  if (fs.existsSync(configPath) && !force) {
    throw new Error(`marbas-project.json already exists at ${absPath}. Use --force to overwrite.`);
  }

  let legacy = {};
  let hadLegacy = false;

  if (fs.existsSync(legacyPath)) {
    hadLegacy = true;
    try {
      legacy = JSON.parse(fs.readFileSync(legacyPath, 'utf8'));
    } catch (err) {
      throw new Error(`Cannot parse .marbas-site-project.json: ${err.message}`);
    }

    const backupDir = path.join(absPath, '.marbas', 'migration-backup');
    fs.mkdirSync(backupDir, { recursive: true });
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    fs.copyFileSync(legacyPath, path.join(backupDir, `marbas-site-project.json.${timestamp}`));
  }

  // Build environments — built-ins plus any legacy-defined env (lib-relevant
  // fields only; CMS-specific baseHref/domain are dropped).
  const envs = {};
  const legacyEnvs = legacy?.environments || {};
  for (const [name, def] of Object.entries({ ...DEFAULT_ENVS, ...legacyEnvs })) {
    envs[name] = { outputName: def.outputName || name, env: def.env || {} };
  }

  // Preserve the legacy default environment as a custom env so a migrated
  // project that built against e.g. "staging" keeps building (no hard break).
  const defaultEnvironment = legacy?.preview?.defaultEnvironment || 'development';
  if (!envs[defaultEnvironment]) {
    envs[defaultEnvironment] = { outputName: defaultEnvironment, env: {} };
  }

  const themeSelected = String(legacy?.theme?.selected || '').trim();
  const themeId = themeSelected ? themeSelected.replace(/\.css$/, '') : null;

  const projectConfig = {
    name: legacy?.name || path.basename(absPath),
    marbasSite: LIB_PKG.version,
    paths: { buildDir: legacy?.paths?.buildDir || './build' },
    defaultEnvironment,
    environments: envs,
    deployTargets: {},
    theme: {
      id: themeId,
      cssMode: legacy?.cssMode || legacy?.theme?.cssMode || 'marbas',
      languageSwitcher: legacy?.theme?.languageSwitcher !== false
    },
    rendering: {
      footerMode: legacy?.rendering?.footerMode || 'globalData',
      headerMode: legacy?.rendering?.headerMode || 'globalData'
    },
    ...(legacy?.i18n ? { i18n: legacy.i18n } : {})
  };

  fs.writeFileSync(configPath, JSON.stringify(projectConfig, null, 2) + '\n');

  return { configPath, hadLegacy, config: projectConfig };
}

const GITIGNORE = `node_modules/
build/
.cache/
.marbas/trash/
.marbas/build-context/
.marbas/migration-backup/
# generated by the build (project webpack configs in _webpack/<env>.js stay tracked)
_webpack/lib-entry.js
_webpack/custom-js-entry.js
`;

// Minimal start page for projects created without --starter.
function indexPage(lang) {
  const german = String(lang).split('-')[0] === 'de';
  const title = german ? 'Willkommen' : 'Welcome';
  const heading = german ? 'Willkommen bei deinem neuen Marbas-Projekt' : 'Welcome to your new Marbas project';
  return `---
layout: base
title: ${title}
pageLanguage: ${lang}
templateEngineOverride: njk,md
---

# ${heading}
`;
}

const STARTER_PAGES_DIR = path.join(__dirname, 'starter', 'pages');
const STARTER_PAGES_EN_DIR = path.join(__dirname, 'starter', 'pages-en');
// Base v2 themes: same legal pages, home/about built from the v2 building blocks (overlaid)
const STARTER_PAGES_V2_DIR = path.join(__dirname, 'starter', 'pages-v2');
const STARTER_PAGES_V2_EN_DIR = path.join(__dirname, 'starter', 'pages-v2-en');
const FAVICONS_DIR = path.join(__dirname, 'assets', 'favicons');

function copyStarterPages(targetPagesDir, lang = 'de', { family = 'classic' } = {}) {
  const primary = String(lang).split('-')[0];
  const sources = [primary === 'de' ? STARTER_PAGES_DIR : STARTER_PAGES_EN_DIR];
  if (family === 'v2') sources.push(primary === 'de' ? STARTER_PAGES_V2_DIR : STARTER_PAGES_V2_EN_DIR);
  for (const src of sources) copyTree(src, targetPagesDir);
}

function copyTree(srcDir, targetPagesDir) {
  const stack = [{ src: srcDir, dest: targetPagesDir }];
  while (stack.length > 0) {
    const { src, dest } = stack.pop();
    fs.mkdirSync(dest, { recursive: true });
    for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
      const srcPath = path.join(src, entry.name);
      const destPath = path.join(dest, entry.name);
      if (entry.isDirectory()) {
        stack.push({ src: srcPath, dest: destPath });
      } else if (entry.name !== '_data') {
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }
}

/**
 * Initialise a new Marbas project at projectPath.
 *
 * @param {object} options
 * @param {string} options.projectPath          Target directory (may exist; refused only if it already contains marbas-project.json, unless force)
 * @param {string} [options.name]               Project name (defaults to directory basename)
 * @param {string} [options.description]        Optional description
 * @param {string} [options.defaultEnvironment] Default build environment (default: "development")
 * @param {boolean} [options.force]             Overwrite if already a Marbas project
 * @param {boolean} [options.starter]           Copy starter pages with example components
 * @param {string} [options.lang]               Default language code (default "de"); non-German → English starter
 * @param {string} [options.theme]              Theme id to activate (also applies its header/nav/footer variants)
 * @param {string} [options.libRoot]            marbas-site package root (theme lookup)
 */
export function initProject({
  projectPath,
  name,
  description = '',
  defaultEnvironment = 'development',
  force = false,
  starter = false,
  lang = 'de',
  theme = DEFAULT_THEME,
  libRoot = path.resolve(__dirname, '../..')
} = {}) {
  const absPath = path.resolve(projectPath);
  const projectName = name || path.basename(absPath);
  const language = String(lang || 'de').trim().toLowerCase();
  if (!/^[a-z]{2}(-[a-z]{2})?$/.test(language)) {
    throw new Error(`Invalid --lang "${lang}". Use a language code like "de" or "en".`);
  }
  let themeFamily = 'classic';
  if (theme) {
    // Throws with a helpful message when the theme does not exist.
    const themeFile = resolveThemeFile({ projectPath: absPath, themeId: theme, libRoot });
    themeFamily = readThemeFamily(fs.readFileSync(themeFile, 'utf8'));
    if (themeFamily !== 'v2') console.warn(`[init] ${classicDeprecationMessage(theme)}`);
  }

  const alreadyInitialised = fs.existsSync(path.join(absPath, 'marbas-project.json'));
  if (alreadyInitialised && !force) {
    throw new Error(
      `Directory already exists: ${absPath}\nUse --force to overwrite.`
    );
  }

  // Directories
  const dirs = [
    absPath,
    path.join(absPath, 'pages', '_data'),
    path.join(absPath, '_components'),
    path.join(absPath, '_theme'),
    path.join(absPath, '_media'),
    path.join(absPath, '.marbas')
  ];
  for (const dir of dirs) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // .gitkeep placeholders for empty dirs
  for (const dir of ['_components', '_theme', '_media']) {
    fs.writeFileSync(path.join(absPath, dir, '.gitkeep'), '');
  }

  // marbas-project.json
  const projectConfig = {
    name: projectName,
    description,
    marbasSite: LIB_PKG.version,
    paths: {
      buildDir: './build'
    },
    defaultEnvironment,
    environments: {
      development: { outputName: 'development', env: {} },
      production: { outputName: 'production', env: {} }
    },
    deployTargets: {},
    theme: {
      id: theme || null,
      cssMode: 'marbas',
      // one language → no switcher; add languages to site.json locale and enable it
      languageSwitcher: false
    },
    rendering: {
      footerMode: 'globalData',
      headerMode: 'globalData'
    }
  };
  fs.writeFileSync(
    path.join(absPath, 'marbas-project.json'),
    JSON.stringify(projectConfig, null, 2) + '\n'
  );

  // _data/site.json
  let siteSettings = getDefaultSiteSettings(absPath, { title: name, lang: language });
  // Only new projects get the site name as seo.siteName — the shared defaults stay empty so that
  // normalizing an existing site.json never injects a folder name into every page title.
  siteSettings.seo.siteName = siteSettings.title;
  if (theme) siteSettings = applyVariantDefaultsToSiteSettings(siteSettings, theme);
  // v2 starter: show the header tagline (example text, only for new starter projects)
  if (starter && themeFamily === 'v2') {
    siteSettings.header.tagline = language.startsWith('de') ? 'Ihr Schwerpunkt · Ihr Ort' : 'Your focus · Your city';
  }
  fs.writeFileSync(
    path.join(absPath, 'pages', '_data', 'site.json'),
    JSON.stringify(siteSettings, null, 2) + '\n'
  );

  // pages/index.md — starter copies example pages, minimal writes a blank index
  if (starter) {
    copyStarterPages(path.join(absPath, 'pages'), language, { family: themeFamily });
  } else {
    fs.writeFileSync(path.join(absPath, 'pages', 'index.md'), indexPage(language));
  }

  // _assets/favicons → copied to the web root by the build (favicon.ico, apple-touch-icon.png)
  const faviconDest = path.join(absPath, '_assets', 'favicons');
  fs.mkdirSync(faviconDest, { recursive: true });
  for (const file of fs.readdirSync(FAVICONS_DIR)) {
    const dest = path.join(faviconDest, file);
    if (!fs.existsSync(dest)) fs.copyFileSync(path.join(FAVICONS_DIR, file), dest);
  }

  // .gitignore
  fs.writeFileSync(path.join(absPath, '.gitignore'), GITIGNORE);
}
